[v1]
"bunyan 0.1.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["bunyan"]
"cargo-about 0.6.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-about"]
"cargo-audit 0.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-check 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-check"]
"cargo-deny 0.16.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deny"]
"cargo-edit 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.95 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-geiger 0.11.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-geiger"]
"cargo-insta 1.41.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-insta"]
"cargo-update 16.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"cargo-watch 8.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"git-cliff 2.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "git-cliff",
    "git-cliff-completions",
    "git-cliff-mangen",
]
"rustlings 6.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustlings"]
"sqlx-cli 0.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-sqlx",
    "sqlx",
]
"just 1.38.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"bacon 3.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"cargo-binstall 1.10.17 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-binstall"]
