return {
  "simrat39/symbols-outline.nvim",
  keys = {
    { "<leader>cs", "<cmd>SymbolsOutline<cr>", desc = "Symbols outline" },
  },
  opts = {
    position = "right",
    autofold_depth = 1,
    symbol_blacklist = {
      "File",
      -- "Module",
      "Namespace",
      "Package",
      -- "Class",
      -- "Method",
      "Property",
      "Field",
      -- "Constructor",
      -- "Enum",
      -- "Interface",
      -- "Function",
      -- "Variable",
      -- "Constant",
      "String",
      "Number",
      "Boolean",
      "Array",
      "Object",
      "Key",
      "Null",
      "EnumMember",
      -- "Struct",
      "Event",
      "Operator",
      "TypeParameter",
      "Component",
      "Fragment",
    },
  },
}
