# cSpell:ignore brightblack unstaged unstage lazygit submodule repos pgup pgdown gitmoji commitizen topo maximised difftool
gui:
  windowSize: "half" # 'normal' | 'half' | 'full'
  nerdFontsVersion: "3"
  timeFormat: 02 Jan 06 15:04 MST

git:
  paging:
    colorArg: always
    externalDiffCommand: difft --color=always
