"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
email = "github@alboh.de"
name = "alboh"

[git]
sign-on-push = true
subprocess = true

[signing]
sign-all = true
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBY6qu2rg/5QELypzwTYiUIbLlNUgMpeFSq8GYfgT40Y"

[[--scope]]
--when.repositories = ["~/Development/dhd"]
[--scope.user]
email = "dp@dhd-audio.de"
name = "Daniel Pfefferkorn"
[--scope.signing]
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFQ9BtDzYgQv1vse+XLSLX2Jrd218eSjrn6wnliahxcw"

[signing.backends.ssh]
program = "/opt/1Password/op-ssh-sign"
allowed-signers = "~/.ssh/allowed_signers"

[ui]
editor = "nvim"
pager = ["sh", "-c", "diff-so-fancy | less -RFX"]
default-command = "st"
diff-editor = ":builtin"
show-cryptographic-signatures = true

[template-aliases]
'format_timestamp(timestamp)' = 'timestamp.ago()'
# 'format_short_cryptographic_signature(sig)' = '''
#   if(sig,
#     sig.status(),
#     "(no sig)",
#   )
# '''

[aliases]
n = ['new']
d = ['diff']

s = ['show']
sp = ["show", "@-"]

# l = ['log', '--limit', '10']
# `jj l` shows commits on the working-copy commit's (anonymous) branch
# compared to the `main` branch
l = ["log", "-r", "(main..@):: | (main..@)-"]
lp = ["log", "-r", "@-"]
la = ["log", "-r", "..@"]
lo = ["log", "-r", "overview"]

# here = ['branch', 'set', '-r', 'HEAD@git']
# mutably = ['--config-toml', 'revset-aliases."immutable_heads()" = "none()"']

[revsets]
# log = "@ | bases | branches | curbranch::@ | @::nextbranch | downstream(@, branchesandheads)"
# log = "stack"

[revset-aliases]
# 'bases' = 'main'
# 'downstream(x,y)' = '(x::y) & y'
# 'branches' = 'downstream(trunk(), branches()) & mine()'
# 'branchesandheads' = 'branches | (heads(trunk()::) & mine())'
# 'curbranch' = 'latest(branches::@- & branches)'
# 'nextbranch' = 'roots(@:: & branchesandheads)'
overview = '@ | ancestors(immutable_heads().., 2) | trunk()'
# stack = "(trunk()-..@) | @::"
# my-unmerged = "mine() ~ ::trunk()"
# my-unmerged-remote = "mine() ~ ::trunk() & remote_branches()"
# not-pushed = "remote_branches().."
