[user]
email = "github@alboh.de"
name = "alboh"

[core]
fsmonitor = 'watchman'

[ui]
editor = "nvim"
# diff-editor = ['scm-diff-editor', '--dir-diff', '$left', '$right']
# diff-editor = 'meld'
# diff-editor = ["kdiff3", "--merge", "$left", "$right"]
merge-editor = [
  'code',
  '--merge',
  '$left',
  '$right',
  '$base',
  '$output',
  '--wait',
]

pager = ["sh", "-c", "diff-so-fancy | less -RFX"]
default-command = "log"

[ui.diff]
format = "git"

[template-aliases]
# 'format_short_id(id)' = 'id.shortest()'
'format_timestamp(timestamp)' = 'timestamp.ago()'

[aliases]
n = ['new']
d = ['diff']
s = ['status']

# l = ['log', '--limit', '10']
# `jj l` shows commits on the working-copy commit's (anonymous) branch
# compared to the `main` branch
l = ["log", "-r", "(main..@):: | (main..@)-"]

# here = ['branch', 'set', '-r', 'HEAD@git']
# mutably = ['--config-toml', 'revset-aliases."immutable_heads()" = "none()"']

# [revsets]
# log = "@ | bases | branches | curbranch::@ | @::nextbranch | downstream(@, branchesandheads)"
#
# [revset-aliases]
# 'bases' = 'main'
# 'downstream(x,y)' = '(x::y) & y'
# 'branches' = 'downstream(trunk(), branches()) & mine()'
# 'branchesandheads' = 'branches | (heads(trunk()::) & mine())'
# 'curbranch' = 'latest(branches::@- & branches)'
# 'nextbranch' = 'roots(@:: & branchesandheads)'
