return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "bash",
        "cmake",
        "css",
        "devicetree",
        "gitcommit",
        "gitignore",
        "glsl",
        "go",
        "graphql",
        "html",
        "http",
        "javascript",
        "json",
        "kconfig",
        "lua",
        "markdown",
        "markdown_inline",
        "meson",
        "ninja",
        "nix",
        "org",
        "prisma",
        "php",
        "regex",
        "scss",
        "sql",
        "svelte",
        "tsx",
        "typescript",
        "vue",
        "wgsl",
        -- "comment", -- comments are slowing down TS bigtime, so disable for now
      })
    end,
  },
}
