[default_session]
# startup_command = "nvim +GoToFile"

[[session]]
name = "hypr config"
path = "~/dotfiles/config/.config/hypr"
startup_command = "nvim userprefs.conf"


[[session]]
name = "tmux config"
path = "~/dotfiles/tmux/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "newsboat"
path = "~/dotfiles/newsboat/.newsboat"
startup_command = "newsboat"


[[session]]
name = "neovim config"
path = "~/dotfiles/nvim/.config/lazyvim"

[[session]]
name = "fish config"
path = "~/dotfiles/fish/.config/fish"
startup_command = "nvim config.fish"

# [[session]]
# name = "wezterm config"
# path = "~/dotfiles/wezterm/.config/wezterm"
# startup_command = "nvim wezterm.lua"

[[session]]
name = "kitty config"
path = "~/dotfiles/config/.config/kitty"
startup_command = "nvim kitty.conf"


[[session]]
name = "sesh config"
path = "~/dotfiles/config/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "local binaries"
path = "~/dotfiles/bin/.local/bin"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"
