return {
  "Bekaboo/dropbar.nvim",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    icons = {
      ui = { bar = { separator = " > " } },
    },
    sources = {
      treesitter = {
        valid_types = {
          "array",
          -- "boolean",
          -- "break_statement",
          -- "call",
          -- "case_statement",
          "class",
          "constant",
          -- "constructor",
          -- "continue_statement",
          -- "delete",
          -- "do_statement",
          "enum",
          -- "enum_member",
          -- "event",
          -- "for_statement",
          "function",
          -- "if_statement",
          "interface",
          -- "keyword",
          -- "list",
          -- "macro",
          "method",
          "module",
          -- "namespace",
          -- "null",
          -- "number",
          -- "operator",
          -- "package",
          -- "property",
          -- "reference",
          -- "repeat",
          -- "scope",
          -- "specifier",
          -- "string",
          "struct",
          -- "switch_statement",
          -- "type",
          -- "type_parameter",
          -- "unit",
          -- "value",
          "variable",
          -- "while_statement",
          -- "declaration",
          -- "field",
          -- "identifier",
          -- "object",
          -- "statement",
          -- "text",
        },
      },
    },
  },
  keys = {
    {
      "<leader>wp",
      function()
        require("dropbar.api").pick()
      end,
      desc = "winbar pick",
    },
  },
}
